version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: andi-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-andi_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-andi_dev_password}
      POSTGRES_DB: ${POSTGRES_DB:-andi_db}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=en_US.utf8 --lc-ctype=en_US.utf8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-andi_user} -d ${POSTGRES_DB:-andi_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - andi-network

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: andi-pgadmin
  #   restart: unless-stopped
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@andi.local}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin_password}
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #     PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
  #     - ./pgadmin/servers.json:/pgadmin4/servers.json
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - andi-network

volumes:
  postgres_data:
    driver: local
  # pgadmin_data:
  #   driver: local

networks:
  andi-network:
    driver: bridge