global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ClickHouse metrics
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:9363']
    metrics_path: /metrics

  # Airflow metrics (if enabled)
  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-webserver:8080']
    metrics_path: /admin/metrics/

  # ETL application metrics
  - job_name: 'andi-etl'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: /metrics
    scrape_interval: 30s

  # System metrics (node exporter if available)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']