version: '3.8'

services:
  langflow:
    image: langflowai/langflow:latest
    container_name: andi_langflow_dev
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@langflow_db:5432/langflow
      - LANGFLOW_AUTO_LOGIN=true
      - LANGFLOW_SUPERUSER=admin@andi.local
      - LANGFLOW_SUPERUSER_PASSWORD=langflow_admin
      - LANGFLOW_SECRET_KEY=your-secret-key-here
      - LANGFLOW_LOG_LEVEL=debug
      - LANGFLOW_HOST=0.0.0.0
      - LANGFLOW_PORT=7860
      - LANGFLOW_OPEN_BROWSER=false
      - LANGFLOW_REMOVE_API_KEYS=false
      - LANGFLOW_SAVE_DB_IN_CONFIG_DIR=false
      - LANGFLOW_LANGCHAIN_CACHE=InMemoryCache
      # AI Service Keys (to be configured)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY:-}
      # Local Ollama Configuration
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - OLLAMA_ENABLED=${OLLAMA_ENABLED:-true}
      - OLLAMA_CIQ_MODEL=${OLLAMA_CIQ_MODEL:-andi-ciq-analyzer}
      - OLLAMA_COACH_MODEL=${OLLAMA_COACH_MODEL:-andi-coach}
      - OLLAMA_REALTIME_MODEL=${OLLAMA_REALTIME_MODEL:-andi-realtime}
      - OLLAMA_TIMEOUT=${OLLAMA_TIMEOUT:-60}
    volumes:
      - ./flows:/app/flows
      - ./custom_components:/app/custom_components
      - langflow_data:/app/langflow
    depends_on:
      - langflow_db
      - redis
    networks:
      - langflow_network
      - andi_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  langflow_db:
    image: postgres:15-alpine
    container_name: andi_langflow_postgres
    environment:
      - POSTGRES_DB=langflow
      - POSTGRES_USER=langflow
      - POSTGRES_PASSWORD=langflow
    volumes:
      - langflow_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - langflow_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: andi_langflow_redis
    ports:
      - "6380:6379"
    volumes:
      - langflow_redis_data:/data
    networks:
      - langflow_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  langflow_data:
  langflow_postgres_data:
  langflow_redis_data:

networks:
  langflow_network:
    driver: bridge
  andi_network:
    external: true
    name: app-database_andi-network