version: '3.8'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: andi-web-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://andi_user:andi_dev_password@andi-postgres:5432/andi_db
      - REDIS_HOST=andi-redis
      - REDIS_PORT=6379
      - OLLAMA_API_URL=http://andi_ollama_cpu:11434
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=development-secret-key-please-change-in-production
      - ASSEMBLY_AI_API_KEY=ec3e29e748504340acb9d50e6149ab6b
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - AZURE_CLIENT_ID=placeholder-azure-client-id
      - AZURE_CLIENT_SECRET=placeholder-azure-client-secret
      - AZURE_TENANT_ID=placeholder-tenant-id
      - EMAIL_SERVER_HOST=smtp.gmail.com
      - EMAIL_SERVER_PORT=587
      - EMAIL_SERVER_USER=your-email@gmail.com
      - EMAIL_SERVER_PASSWORD=your-gmail-app-password
      - EMAIL_FROM=your-email@gmail.com
      - SENTRY_DSN=
      - SENTRY_ORG=
      - SENTRY_PROJECT=
      - STORAGE_PROVIDER=azure
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://andi-azurite:10000/devstoreaccount1;
      - AZURE_STORAGE_CONTAINER_NAME=andi-media
    volumes:
      - ./.env.local:/app/.env.local:ro
      - ./src:/app/src:delegated
      - ./public:/app/public:delegated
      - ./uploads:/app/uploads:delegated
      - /app/.next
    networks:
      - andi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  andi-network:
    external: true
    name: app-database_andi-network